language: python
python:
  - "3.6"
services:
  - postgresql
env: # => 4
  -DJANGO_ENV=production DATABASE_URL = postgres://postgres@localhost/test_db
install:
  - pip install -r requirements/requirements.txt
before_script:
  - psql -c 'create database test_db;' -U postgres
# command to run tests
script:
  - python manage.py test
