sudo: false
language: python
python:
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
    - libgdal-dev
install:
  - pip install -r requirements.txt
before_script:
 # check gis
  - gdal-config --version
  - gdal-config --cflags
  - psql -U postgres -c "create extension postgis"
  # set up postgresql
  - psql -c 'create database test_db;' -U postgres
# command to run tests
script:
  - python manage.py test
