# Generated by Django 2.0.2 on 2018-02-10 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        ('org_units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedentityattribute',
            name='owned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackedentity',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='tracked_entities', to='modules.TrackedEntityAttribute'),
        ),
        migrations.AddField(
            model_name='trackedentity',
            name='owned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stage',
            name='module',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='modules.Module'),
        ),
        migrations.AddField(
            model_name='stage',
            name='next_stages',
            field=models.ManyToManyField(blank=True, related_name='_stage_next_stages_+', to='modules.Stage'),
        ),
        migrations.AddField(
            model_name='stage',
            name='observation_forms',
            field=models.ManyToManyField(blank=True, related_name='stages', to='modules.ObservationForm'),
        ),
        migrations.AddField(
            model_name='module',
            name='authorized_org_units',
            field=models.ManyToManyField(blank=True, related_name='available_modules', to='org_units.OrgUnit'),
        ),
        migrations.AddField(
            model_name='module',
            name='owned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventdataelement',
            name='data_element',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='modules.DataElement'),
        ),
        migrations.AddField(
            model_name='eventdataelement',
            name='stage',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_data_elements', to='modules.Stage'),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='owned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
