# Generated by Django 2.0.2 on 2018-03-02 11:19

from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('org_units', '0002_orgunit_owned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunit',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgunit',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgunit',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=None, related_name='children', to='org_units.OrgUnit'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgunit',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
